name: aquaroute
description: "A Fleet Tracking, Telemetry, and Route Optimization System"
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.3.2
  
  # Networking & Backend
  supabase_flutter: ^2.0.0
  http: ^1.1.0
  
  # Maps & Geolocation
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  
  # Utilities
  flutter_dotenv: ^6.0.1 # For securing your Google/Supabase Keys
  intl: ^0.20.3          # For formatting dates/currencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true